AWSTemplateFormatVersion: "2010-09-09"
Description: ICPA Lambda observability defaults (ADOT layer + env)

Parameters:
  AdotLayerArn:
    Type: String
    Default: arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python-amd64-ver-1-20-0:3

Resources:
  LambdaDefaults:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Placeholder-For-Defaults
      Runtime: python3.13
      Handler: index.handler
      Code:
        ZipFile: |
          def handler(event, context):
              return {"status": "placeholder"}
      Layers:
        - !Ref AdotLayerArn
      Environment:
        Variables:
          OTEL_SERVICE_NAME: icpa
          OTEL_TRACES_SAMPLER: parentbased_traceidratio
          OTEL_TRACES_SAMPLER_ARG: "0.1"
          OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4317
