AWSTemplateFormatVersion: "2010-09-09"
Description: ICPA Lambda observability defaults (ADOT layer + env)

Parameters:
  AdotLayerArn:
    Type: String
    Default: arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python-amd64-ver-1-20-0:3

Resources:
  OtelServiceName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /icpa/otel/service_name
      Type: String
      Value: icpa
      Description: Default OTEL service name for ICPA Lambdas

  OtelTracesSampler:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /icpa/otel/traces_sampler
      Type: String
      Value: parentbased_traceidratio
      Description: Default OTEL trace sampler

  OtelTracesSamplerArg:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /icpa/otel/traces_sampler_arg
      Type: String
      Value: "0.1"
      Description: Default OTEL trace sampler arg

  OtelExporterEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /icpa/otel/exporter_otlp_endpoint
      Type: String
      Value: http://localhost:4317
      Description: Default OTEL exporter endpoint for Lambda ADOT

Outputs:
  AdotLayerArn:
    Description: ADOT Lambda Layer ARN to attach to functions
    Value: !Ref AdotLayerArn
